### ISSUE TITLE
pretrained weights for RGB?

### ISSUE THREAD

**Issue by dflateau** [pancakewaffles/metasrgan-tutorial#2]
It seems liket the pretrained weights with the tutorial are for greyscale only? Do you have weights for the tutorial for RGB images?

**Comment by pancakewaffles** [comment]
I do have weights for the Meta-SRGAN generator for RGB images, but I am not too too sure how well trained they are, as they were trained some time ago. They might not be that well trained. Nevertheless, I have uploaded them as 

However, I dug around and actually found a full tutorial I wrote that describes Meta-SRGAN and training it, with a step-by-step walkthrough similar in style to the Tutorial_Super_Resolution.ipynb in this repo. I have answered that in greater detail in your other question. So look at that for an answer.

**Comment by dflateau** [comment]
Got it - thanks so much again!
